name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0
  pull_request:
    branches: [ main, master ]

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip this job for tag pushes, as we'll handle that in the release job
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    timeout-minutes: 10  # Ensure job completes within 10 minutes

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Shallow clone for faster checkout
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      
    - name: Run tests
      run: mvn test

  release:
    runs-on: ubuntu-latest
    # Only run this job for tag pushes
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    timeout-minutes: 10  # Ensure job completes within 10 minutes
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for version comparison
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven
    
    - name: Get tag name
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Verify version is higher than previous releases
      run: |
        # Extract version number without the 'v' prefix
        CURRENT_VERSION=${GITHUB_REF#refs/tags/v}
        echo "Current version: $CURRENT_VERSION"
        
        # Get all previous version tags
        git fetch --tags
        PREV_VERSIONS=$(git tag -l "v*" | grep -v ${{ steps.get_tag.outputs.TAG }} | sed 's/^v//')
        
        if [ -z "$PREV_VERSIONS" ]; then
          echo "No previous versions found. This is the first release."
          exit 0
        fi
        
        # Check if current version is higher than all previous versions
        for VERSION in $PREV_VERSIONS; do
          # Use sort with version sort flag to compare versions
          if [ "$(printf '%s\n' "$CURRENT_VERSION" "$VERSION" | sort -V | head -n1)" != "$CURRENT_VERSION" ]; then
            echo "Current version $CURRENT_VERSION is higher than or equal to previous version $VERSION. Continuing..."
          else
            echo "Error: Current version $CURRENT_VERSION is lower than previous version $VERSION"
            echo "Please use a higher version number."
            exit 1
          fi
        done
        echo "Version check passed. Current version is higher than all previous versions."
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_tag.outputs.TAG }}
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
